version: "3.7"
services:
  users_db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    container_name: users_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - usersdb-data:/var/lib/mysql

volumes:
  usersdb-data:
